### ISSUE TITLE
Certificate created is not valid before future date

### ISSUE THREAD

**Issue by meshde** [mlebkowski/nassau-https-proxy#6]
In some cases, the certificate created has a `Not Valid Before` date a few hours into the future.

My system timezone is configured as IST (UTC +5:30), so a certificate created on `10 November 2019 01:30 am IST` has a `Not Valid Before` date of `10 November 2019 05:30 am IST`.

**Comment by mlebkowski** [comment]
Are you using a version after this patch? 59d741f9d4833ab47e97b5c9a7206a1396736349

I had the same issue and basically rewrote the way certs are generated and that fixed the problem for me.

**Comment by meshde** [comment]
Actually, the problem was in the way the start date was created. For example, if my system date right now is `10 November 2019 01:30 am IST`, the command `date +"%y%m%d000000Z"` would generate `191110000000Z` (which is `10 November 2019 00:00 UTC` or `10 November 2019 05:30 am IST`), which is technically in the future.

I have raised #7 , which basically tells the `date` command to use UTC while generating the date.

**Comment by mlebkowski** [comment]
Here you go, I published ver 1.0.4 with your patch: https://www.npmjs.com/package/nassau-https-proxy

Thanks!
